run:
  timeout: 5m
  go: "1.21"
  skip-dirs:
    - "vendor"
    - "test_data"
    - "multinode_logs"
    - "burn_in_logs"
    - "node1_data"
    - "node2_data"

linters-settings:
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: "github.com/lpreimesberger/shadowy"
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 20
  nestif:
    min-complexity: 4
  lll:
    line-length: 120
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  gomod:
    go-version: "1.21"
  
linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - golint
    - gomnd
    - gomod
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  disable:
    - gochecknoglobals
    - gocognit
    - testpackage

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
        - lll
    - path: cmd/
      linters:
        - gochecknoinits
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
    - text: "G204: Subprocess launched with variable"
      linters:
        - gosec
    - source: "//nolint"
      linters:
        - lll
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true